title: BadSeed
author: Xixi & Tongtong
url: https://thebadseed.fr
email: zqt1998@gmail.com
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts
