# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'Pour Pierre',  url: 'pour-pierre'}
- {name: 'Stomping on the World', url: 'stomping-on-the-world'}
- {name: 'Work in Progress',       url: 'sample-posts'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:zqt1998@gmail.com'}

# Customize site text
  #pagination:
  #next_page: 'Newer'
  #previous_page: 'Older'
